### PR TITLE
Desktop Duplication API

### PR DESCRIPTION
**Pull request by BenNottelling**
"@BenNottelling Thanks for looking after this project, my code isn't the best since I've never used c++ before, anyway...

I implemented support for a external grabber via a DLL in my fork since I couldn't get desktop duplication working in VS2010, it's a nice feature to support since you can send a customise the output without needing to build the project again.

Other minor changes:

Only grab when a client is connected.
RequireAdministrator execution - This is so you don't lose all control if you open task manager."

P.S, thanks Olly!

### CODE REVIEW

**Comment by ollydev** [comment]
You're right. I committed quite untested code, and did not upload the desktop duplication binary. 

Next time i'm free I will fix this all and make it more "proper". 😃

**Comment by BenNottelling** [comment]
Awesome! Thank you! 😁

**Comment by BenNottelling** [comment]
If you have the time, I'd really appreciate it if you could upload the DLL here so I can test the changes.. I'm not expecting fixed code, just an upload as a comment would be great @ollydev

**Comment by ollydev** [comment]
@BenNottelling 

jsmpeg-vnc: https://github.com/ollydev/jsmpeg-vnc
plugin: https://github.com/ollydev/jsmpeg-vnc-desktop-duplication/releases

**Comment by BenNottelling** [comment]
Awesome! This works :D 
okay, so I'll do some testing on my own but right from the start steaming performance on the desktop is about double for me, but I can't get above 30FPS. I haven't tried anything else though and I think maybe it's a CPU thing. Even then 30FPS isn't bad considering my server's specs.
2X Intel xeon X5660 (6 core, 12 threads each) <-- Slow in single threaded performance due to it's age.
72GB of a ram
NVIDA Quadro 2000 <-- Slow (about an intel UHD 630)

**Comment by BenNottelling** [comment]
Oops, I forgot to check and see if it build for debugging 😂
Oh well, we will find out later. Thank you for the pull request!

**Comment by ollydev** [comment]
Try playing a youtube video (or similar) so there are actually screen updates. 

- Desktop duplication only gives you a image when there has been a update, and I set [TimeoutInMilliseconds](https://docs.microsoft.com/en-us/windows/desktop/api/DXGI1_2/nf-dxgi1_2-idxgioutputduplication-acquirenextframe) to 16ms, so if there is no screen updates it's always going to take 16ms for a frame and then the time for encoding/scaling. Just tested and I get around 30fps when there is no activity on my desktop.

**Comment by BenNottelling** [comment]
Thanks @ollydev , I tried that and it seems to work, but I have seen two issues now. (I really should have tested more before merging)
First, I can't capture windows (and use the grabber) it just captures the whole desktop, and, and might be an issue on my end, but on my server it no longer sends a video feed when using the grabber DLL. This happened after a restart & update though so I'm not sure if that's an issue from this PR

**Comment by ollydev** [comment]
"First, I can't capture windows (and use the grabber) it just captures the whole desktop."

Yeah, I only made the grabber dll for capturing the whole desktop. BitBlt was extremely fast for me when capturing a window, not sure there is any gain to have from using deskop duplication the cropping out a window?

**Comment by BenNottelling** [comment]
I believe it would help with this: https://github.com/phoboslab/jsmpeg-vnc/issues/28 (an issue I've seen and I also believe will pop up more with new apps & games)

**Pull request merged**
